### ISSUE TITLE
Why delete this variable in the latest version

### ISSUE THREAD

**Issue by stonedreamforest** [zyantific/zydis#123]
![image](https://user-images.githubusercontent.com/16742566/62844438-0137ff80-bcf4-11e9-8d00-be053902252e.png)

-----

I had not found a replacement variable in the latest version

**Comment by flobernd** [comment]
We decided to remove this field, because it is redundant. The user passes the data buffer to `ZydisDecoderDecodeBuffer` anyways, which means he already has access to the data.

There are good use cases where you need the byte-data connected to the decoded instructions, but bytewise deep-copying it like we did it before was as well bad in terms of performance.

If you need to store the data with the instruction, I would go for something like this:
```c
typedef struct MyInstruction_
{
    ZydisDecodedInstruction instruction;
    ZyanU8* data;
    // or maybe `ZyanU8 data[ZYDIS_MAX_INSTRUCTION_LENGTH]` if you work with 
    // temporary buffers
} MyInstruction;

...

MyInstruction my_instr;
my_instr.data = buffer; // or `memcpy` if you work with temporary buffers
ZydisDecoderDecodeBuffer(&decoder, &my_instr.instruction, buffer, ...);

list.push_back(my_instr);
```
