### ISSUE TITLE
ZydisRegister and ZydisRegisterClass defined register type is missing MSRs

### ISSUE THREAD

**Issue by wonderzdh** [zyantific/zydis#125]
xed:
509 RDMSR RDMSR SYSTEM BASE PENTIUMREAL ATTRIBUTES: NOTSX RING0 
4 0 REG0 SUPPRESSED W REG INVALID EAX 
1 REG1 SUPPRESSED W REG INVALID EDX 
2 REG2 SUPPRESSED R REG INVALID ECX 
3 REG3 SUPPRESSED R REG INVALID MSRS 

But there is no MSRs in the operand of zydis.

**Comment by flobernd** [comment]
Hi there, please take a look at #34 for the register-classes in general.

The MSRs in general are missing, because there is no reliable way to statically describe all side effects without knowing the exact execution context of the current system and its complete state. It might be possible for some instructions and MSRs, but for the majority it‘s not. We decided to rather don‘t include the MSRs at all than providing partial/incorrect information.

**Comment by wonderzdh** [comment]
Ok, I understand why msr is not included, but I recommend adding some comments to the ZydisRegisterClass structure to understand this behavior immediately.

**Comment by flobernd** [comment]
> I recommend adding some comments to the ZydisRegisterClass structure to understand this behavior immediately

I'll add that to my todo list.
