### ISSUE TITLE
(small) Bug in decoding some instructions

### ISSUE THREAD

**Issue by Artifere** [zyantific/zydis#132]
Hello,
I am working with Zydis, and I think I have found some bug.
./ZydisInfo -32 0F 1A 24 05 00 00 00  gives output NO_MORE_DATA
However, no matter what we put for the 8th byte,
./ZydisInfo -32 0F 1A 24 05 00 00 00 xx yield BAD_REGISTER
=> the BAD_REGISTER should be announced earlier (as early as with the first bytes I think).

Expected output (if I am correct):
./ZydisInfo -32 0F 1A 24 should yield BAD_REGISTER (or ENCODING_ERROR)

Similar correct output:
./ZydisInfo -32 0F 1A 23 does yield BAD_REGISTER
 I founded some  7 bytes which, as the beginning of instruction yield a 

Congratulations for Zydis, the code is nice to read and understandable, and the pretty printing for the instructions is awesome :-)

**Comment by athre0z** [comment]
This instruction `bndldx` is ModRM encoded and [ModRM = 0x24 hits the SIB case](https://www.sandpile.org/x86/opc_rm.htm) (requires a SIB byte). [SIB = 0x05](https://www.sandpile.org/x86/opc_sib.htm) requests another 4 bytes as disp. ModRM decoding is performed before register constraints are checked, which is why you receive `NO_MORE_DATA` here instead of `BAD_REGISTER`.

In essence, the `0F 1A 24 05 00 00 00` instruction has two encoding errors -- it's too short as well as having unallowed registers. The pretty much reduces the issue to whether there should be some kind of precedence for reporting different kind of decoding errors. 

Personally, I don't think the current behavior is much of an issue. The current code allows for having all constraints checked in a central place where all information of the instruction is already present, while immediately reporting any error as soon as it is somehow possible to detect would require duplicating and spreading these checks all over the decoder.

As a side note, IIRC, the instruction prefetcher / decoder in hardware employs a similar behavior where it will first fetch all bytes required for ModRM encoding and only afterwards check validity of register/instruction combinations. If you were to place that incomplete instruction immediately before a guard page, I'd expect that you'll receive a memory protection error rather than an #UD.

**Comment by flobernd** [comment]
Zydis uses the early exit strategy wherever it is possible to maximize performance. Even if the register is encoded earlier in the instruction, the decoding of it still happens later.

I think the mistake you made was assuming that all the fields in the encoded instruction will be decoded from "left - to - right" in a specific order. As Joel already said this is not the case.
