### ISSUE TITLE
Decoder fails to decode some weird instructions

### ISSUE THREAD

**Issue by 0xd4d** [zyantific/zydis#133]
Version: latest master = 4d4fe4c293c5438f32688b14b29017ae3f48369e

----------------------------

Can't decode these instructions. `REX.X` bit should be ignored.

- `66420F1ACA` = `bndmov` = unused `REX.X` bit is set
- `66420F1BCA` = `bndmov` = unused `REX.X` bit is set

----------------------------

Can't decode these instructions. Rounding control should be ignored.

Intel SDM: `EVEX.W0 version: attempt to encode this instruction with EVEX embedded rounding is ignored.`

- `62E10F182AD3` = `vcvtsi2sd` gpr32 with ignored rc bits
- `62E10F187BD3` = `vcvtusi2sd` gpr32 with ignored rc bits

----------------------------

These decode without errors in minimal mode because `ZydisDecodeOperands()` isn't called:

- `0F1A0D34125AA5`
- `0F1B0D34125AA5`

**Comment by flobernd** [comment]
Hi there,

first of all thanks for reporting these issues. Correctness is very important for us.

> Can't decode these instructions. REX.X bit should be ignored

You are correct I guess. Not entirely sure why I put a check to actively prevent `REX.X` for `BND` registers. The `.X` component is only used to extend `RM` encoded registers for `EVEX/MVEX` anyways and should not affect `BND`.

Fixed in: https://github.com/zyantific/zydis/commit/d7ba09ae06f8919eee7e8507b6a084efbd8d8cbd

> Can't decode these instructions. Rounding control should be ignored.

You are correct here as well. I had a constraint requiring all `E10NF` exception-class instructions to have `EVEX.B` set to `0` in the instruction-editor. I removed that condition to allow these two exceptions.

Fixed in: https://github.com/zyantific/zydis/commit/5f2dde88883c7c87bf5ab69ab2ea4e97012d1a5b

> These decode without errors in minimal mode because ZydisDecodeOperands() isn't called

Will check this case later today.

**Comment by flobernd** [comment]
Fixed the last problem as well by adding a new constraint for `MIB` memory operands to disallow relative addressing.

**Comment by 0xd4d** [comment]
I think your last fix forgot the 64-bit check:

- `0F1A0D34125AA5`: fails to decode in 32-bit mode now

**Comment by flobernd** [comment]
> I think your RIP-rel fix forgot the 64-bit check

Oh well .. seems like I'm really not concentrated today. Thanks for reporting again. Should be fixed now.
