### ISSUE TITLE
difference or advantage over capstone ?

### ISSUE THREAD

**Issue by KnoooW** [zyantific/zydis#15]

**Comment by flobernd** [comment]
Capstones strength is its support for multiple ISAs. This is great for quickly getting a textual representation of an instruction, but it does not provide simple access to more specific instruction details.

## Specialization ##
Zydis focuses on just the X86-64 ISA and allows you to access **a lot of** meta-info ([ZydisInfo.c](https://github.com/zyantific/zydis/blob/master/tools/ZydisInfo.c)), including all internal encoding details (like the decoded bits of `MODRM`, `SIB`, `REX`, `VEX`, ...).

Why would you need these details?
- You can easily relocate instructions with relative immediates (`JMP`, `CALL`, ...) or `RIP`-relative memory operands
  - Zydis sets the `ZYDIS_ATTRIB_IS_RELATIVE` for these instructions and provides you access to the raw address-offset and -size
  - This makes it plain easy to write a generic hook library for example
- You have access to **all** side-effects of an instruction which allows you to implement advanced tools like emulators, PIN-tools, packers/obfuscators, etc
  - Zydis provides info about every accessed operand including implicitly used registers and the specific access mode (read, write, conditionally read, ...)
  - Zydis provides advanced AVX(-512) info about the broadcast-mode, the embedded writemask, rounding-mode, sae and even the type, size and number of (vector-)elements stored in / loaded from a single operand
  - Zydis provides info about affected CPU-flags (well, this one is implemented in Capstone too)

## Performance ##
Zydis is optimized for high performance (while still having an exceptional small file-size overhead):
![Benchmark](http://i.imgur.com/DnQFx4I.png)
_Benchmark executed on a 2016 MacBook Pro (less is better)_

Please keep in mind this is with formatting to human-readable format — which most tools that disassemble tons of code don't even need. With decoding only, Zydis is about 5 times faster. We can't provide a useful diagram here because Capstone lacks support for omitting instruction formatting.

## Customizability ##
The Zydis instruction-formatter supports many inbuilt formatting options and can be fully customized using hook functions ([FormatterHooks.c](https://github.com/zyantific/zydis/blob/master/examples/FormatterHooks.c)).

## Our main goals ##
- Correctness (always feel free to report any bug or incorrect behavior)
- Completeness (aka. support for all known X86-64 ISA-extensions)
- Performance
- Simplicity
