### ISSUE TITLE
Follow branches and do not disassemble data areas

### ISSUE THREAD

**Issue by dave-griffiths** [zyantific/zydis#152]
I am using Zydis to disassemble JIT compiled code blocks produced by OpenJDK. We know the start and end locations but it can happen sometimes that there is an unconditional jump over a data area inside the code block. Zydis currently tries to disassemble the data area and gives up when it fails. It would be nice if it could follow such unconditional branches (assuming they are still within the code block) and maybe earlier conditional branches and thus avoid trying to disassemble the data area.

Zydis is pretty cool though.

**Comment by athre0z** [comment]
Hi Dave, thanks for reaching out to us!

I'm afraid that recursive traversal disassembly, which is what you are describing there, is unfortunately out of scope for Zydis. What we provide is an instruction decoder and formatter upon other projects can build in order to implement whatever kind of disassembler they want. You give it a pointer and it tells you what instruction you are looking at.

The example in our README implements a simple linear sweep disassembler, simply bumping forward the read pointer by the instruction length. What you are looking for is a recursive traversal disassembler. Doing recursive disassembly in a way that works on cross-platform, cross-language and cross-compiler binaries is a task that is so hard that, if you want to do it right, is probably comparable in complexity to the whole Zydis project without it, if not more complex.

**Comment by dave-griffiths** [comment]
Oh wow, fair enough. Yes, my code is based on your linear disassembler I think. I guess I could have a go myself - because the code is produced by a JIT compiler there should be limited ways in which branches occur within a code block. But thanks for the quick reply.

**Comment by athre0z** [comment]
Yes, recursive disassembly for one particular JIT should be comparably simple. Properly following switch tables (not sure if Java JIT will generate such, but I would guess it does) will still at least require some basic control flow graph construction, value range analysis and register + constant tracking however. If I were you, I'd just declare that out-of-scope and only follow simple control flow.
