### ISSUE TITLE
Is there a function similar to cs_insn_group in capstone?

### ISSUE THREAD

**Issue by taodaqiao** [zyantific/zydis#169]
if (cs_insn_group(handle, insn, CS_GRP_JUMP))
 if (cs_insn_group(handle, insn, CS_GRP_CALL))
 if (cs_insn_group(handle, insn, CS_GRP_RET))

**Comment by flobernd** [comment]
The meta-data struct contains the instruction category:
https://github.com/zyantific/zydis/blob/64dfd11e57cdfa7cb62dd41d357ee0b0d33b7a8c/include/Zydis/Generated/EnumInstructionCategory.h

Maybe this is sufficient for your needs.

Otherwise you can write your own helper function like e.g. here:
https://github.com/zyantific/zyan-hook-engine/blob/176e2c98f681404a22b5062abea847c6eb529f08/src/Relocation.c#L291
