### ISSUE TITLE
Fix INVLGPA pseudo-memory register operand

### ISSUE THREAD

**Issue by flobernd** [zyantific/zydis#181]
`0F01DF` is decoded as `invlpga eax, ecx` in 64-bit mode. But it should be `invlpga rax, ecx` according to the manual stating "The portion of RAX used to form the address is determined by the effective address size".

**Comment by tremalrik** [comment]
Doing a few checks with the AMD system instructions, I found one other instruction where effective address size is not properly handled: `PVALIDATE`.

"ZydisInfo -32 F2 0F 01 FF" returns `pvalidate rax, ecx, edx` - the first operand should be `eax` for 32-bit address sizes.

**Comment by flobernd** [comment]
Funny, I was just about to fix this issue 😋 Thanks for the addition. I will change these operands from opsize-scale to adsize-scale.

**Comment by flobernd** [comment]
Fixed in https://github.com/zyantific/zydis-db/commit/af29550047f2f1f46786a5cb12807c7437e68581

Will regenerate and push the tables all together after some more fixes.

**Comment by mappzor** [comment]
Is `invlpga` even possible with address_size = 16? It unconditionally accesses `ecx` register and that suggests it's not possible, so usage in 16-bit protected mode would require address size override. In that case `"address_size": "!16"` would be required here.

`invlpgb` is a similar case and it does not allow address_size =16 according to database file. By the way 2 definitions of `invlpgb` could be merged into one by replacing `eax/rax` with `osz_ax` and using `"address_size": "!16"`.

**Comment by tremalrik** [comment]
For `INVLPGA`, the operand provided in `ecx` is not a memory address and is as such not affected by address size.

There doesn't seem to exist anything in the description of `INVLPGA` or `INVLPGB` (or `PVALIDATE` for that matter) in the [AMD APM](https://www.amd.com/system/files/TechDocs/40332.pdf) that actually prevent these instructions from being used with an address size of 16.

**Comment by mappzor** [comment]
> For `INVLPGA`, the operand provided in `ecx` is not a memory address and is as such not affected by address size.

True, I should mention operand size when talking about `ecx`. Seeing 32-bit register referenced in 16-bit mode without any overrides is a bit strange but I guess it should be allowed here as nothing clearly forbids that. Unfortunately I can't test it on real hardware.

This leads to conclusion that current fixes for `invlpga` and `pvalidate` are ok, but `invlpgb` needs definition merging and `asz_ax` for 1st operand. That would allow 16-bit `address_size` which is currently forbidden here.

**Comment by flobernd** [comment]
I was actually wondering about the 16-bit address size as well while doing the fix. Thanks for the discussion and clarification.

Going to have a look at the `invlpgb` now.

**Comment by tremalrik** [comment]
Looking at a few more AMD system instructions, `VMRUN` and `VMSAVE` also appear to be instructions where the AMD APM appears to allow a full set of address sizes for the implicit operand in AX/EAX/RAX. Zydis does not appear to recognize 67H prefix for `VMRUN`, and does not list the implicit AX/EAX/RAX operand at all for `VMSAVE`. As far as I can tell, both of these instructions should be taking the same operands and operand-size behavior as `VMLOAD`, which is handled correctly.

**Comment by flobernd** [comment]
@tremalrik 

After checking the AMD APM I think it would even be better to replace the implicit `AX/EAX/RAX` by an implicit memory operand `[AX/EAX/RAX]` instead. Do you have any concerns?

Seems like `vmrun` and `vmload` reads a memory block from `[AX/EAX/RAX]` and `vmsave` writes to the memory location.

**Comment by mappzor** [comment]
This would probably be the most uncommon choice for those instructions. APM itself uses register syntax (`rAX`). NASM accepts no operands, LLVM uses eax/rax or no operand, GCC inline assembly uses eax/rax.

Also this is an example of a very complex semantics. First of all, address here is always physical and that's something you wouldn't expect from typical load/store-like memory operands. One could argue that the fact of saving this physical address taken from rAX in some architecturally non-exposed internal register is the major reason for having this operand in the first place, just to show the source of this value (along with the fact that it scales with address size). Reads/writes from/to this 4KB block with implementation-defined internal structure are complex side effects that cannot be expressed using regular operand syntax. I don't think standard `[memory]` does justice to those instructions and is rather unintuitive (Intel's counterparts like `VMXON` use it but those operands are explicit and physically encoded as ModRM memory operands, so that's a different case).

**Comment by flobernd** [comment]
@mappzor 

Thanks for your detailed answer. Now knowing these facts, I agree with you and will keep the implicit register operands and make them visible for all of the instructions.

**Comment by flobernd** [comment]
Fixed with https://github.com/zyantific/zydis/commit/2ab6a5ccb49043e077bcb2559893b1944f8e0a09
