### ISSUE TITLE
Only x86, x64?

### ISSUE THREAD

**Issue by lab313ru** [zyantific/zydis#21]
Hi,

Is it possible that someday you'll add other platforms that the Capstone supports?

**Comment by flobernd** [comment]
There are currently no plans for Zydis to support other architectures in a "capstone-like" manner (with abstraction layer).

Our library focuses on correctness and completeness instead of multi-architecture support (quality > quantity), but we *might* release a second (dedicated) disassembler-library for ARM in the future.
