### ISSUE TITLE
Improve segment override handling

### ISSUE THREAD

**Issue by flobernd** [zyantific/zydis#231]
Current segment override handling still is not perfect right now. 

## General Segment Override Handling in 64-bit Mode

In 64-bit mode, any segment override prefix except for FS/GS is ignored, but Zydis still decodes and prints the ignored segments, if no actual FS/GS prefix is prsent. E.g.: 

```
-64 3E 2E 62 D6 6E 5E D6 49 4D vfmulcph zmm1 {k6}, zmm2, dword ptr cs:[r9+0x134] {1to16}
```

If FS/GS is used, it is favored even if it's not the last prefix of the group (which is fine, but probably not the most intuitive thing):

```
-64 64 2E 62 D6 6E 5E D6 49 4D vfmulcph zmm1 {k6}, zmm2, dword ptr fs:[r9+0x134] {1to16}
```

### Enhancement do do

Ignore non FS/GS prefixes in 64-bit mode entirely.

**Comment by mappzor** [comment]
Another issue with segment overrides is current handling of `ZYDIS_ATTRIB_ACCEPTS_SEGMENT` attribute. This attribute can be set only for `ZYDIS_INSTRUCTION_ENCODING_LEGACY` instructions because only `ZydisInstructionDefinitionLEGACY` exposes `accepts_segment` bit, so you will never have this attribute set for e.g. VEX-encoded instructions that may have overrides properly decoded and accepted. I think `accepts_segment` should be a member of `ZYDIS_INSTRUCTION_DEFINITION_BASE`.

**Comment by flobernd** [comment]
Reopened to remember taking care of the comment issue.

**Comment by flobernd** [comment]
@mappzor I created a PR for the missing part: https://github.com/zyantific/zydis/pull/247
