### ISSUE TITLE
Cant encode using ZYDIS_ENCODABLE_BRANCH_TYPE_NEAR32

### ISSUE THREAD

**Issue by ZehMatt** [zyantific/zydis#266]
```cpp
ZydisEncoderRequest req{};
req.mnemonic = ZYDIS_MNEMONIC_JMP;
req.branch_type = ZydisEncodableBranchType::ZYDIS_ENCODABLE_BRANCH_TYPE_NEAR32;
req.operand_count = 1;
req.operands[0].type = ZYDIS_OPERAND_TYPE_IMMEDIATE;
req.operands[0].imm.u = 0xFF;
```
When specifying NEAR32 I sort of expected it to encode ```jmp <rel32>``` considering 0xFF is in range but it appears I have to either specify ZYDIS_ENCODABLE_BRANCH_TYPE_NEAR64 or ZYDIS_ENCODABLE_BRANCH_TYPE_SHORT.

Also to my understanding there is no encoding variant that encodes 64 bit relative address.

**Comment by mappzor** [comment]
Here's my comment explaining what branch type is: https://github.com/zyantific/zydis/pull/254#discussion_r739657745. Unfortunately even that comment wasn't entirely accurate. While the **purpose** is to let user specify the size of relative immediate, it isn't done directly but in terms of effective operand size. So actually branch type is type + eosz. Current behavior is expected one because `ZydisInfo.exe -64 E9FF000000` reports `EOSZ: 64`. That's not very intuitive, I know.

I guess documentation for `ZydisEncodableBranchType` and `branch_type` field inside `ZydisEncoderRequest` should better explain it assuming `branch_type` manages to survive future changes. We still have to discuss what to do with it (we decided to discuss it after merging #254). I guess we'll have to make it a part of a bigger discussion about all relatives (rip-rel and imm-rel).

**Comment by flobernd** [comment]
Let's just keep this issue open for now as a reminder to discuss above topics.
