### ISSUE TITLE
Consider reworking branch types in the encoder

### ISSUE THREAD

**Issue by athre0z** [zyantific/zydis#268]
This is a continuation of the discussion [here](https://github.com/zyantific/zydis/pull/254#discussion_r739544494). Thinking about this for a bit longer and having gained some usage experience with the encoder, I withdraw my initial suggestion. 

When encoding branches, a user must currently explicitly choose a very specific branch type like `ZYDIS_ENCODABLE_BRANCH_TYPE_NEAR64` in the request, which is quite inconvenient for code generation. I think that it would be preferable to instead keep the decoder type as-is, and instead split the `ZydisEncodableBranchType` type into two separate fields in the encoder request such as:

```c
enum ZydisBranchWidth {
  ZYDIS_BRANCH_WIDTH_NONE,
  ZYDIS_BRANCH_WIDTH_16,
  ZYDIS_BRANCH_WIDTH_32,
  ZYDIS_BRANCH_WIDTH_64
};

struct ZydisEncoderRequest {
  ZydisBranchType branch_type; // reusing the decoder type
  ZydisBranchWidth branch_width;
  // remaining fields omitted
};
```

`ZYDIS_BRANCH_TYPE_NONE` and `ZYDIS_BRANCH_WIDTH_NONE` would mean "infer" to the encoder. `ZYDIS_BRANCH_TYPE_NONE` specifically would mean "infer whether near or short", but never consider "far", which must be requested explicitly. I'd argue that in 99% of cases, users will want some variation of a near/short branch. In a semantic encoder interface, I'd further argue that it should be the encoder that picks a good branch variant for the provided offset.

The upside with the current approach is that it's impossible to specify invalid combinations, reducing the amount of validation required. I assume that's what you meant with "needing a tuple type" in your comment [here](https://github.com/zyantific/zydis/pull/254#discussion_r739657745). However, I personally don't think this warrants the downsides. If such a tuple type is truly required, we should keep it internal to the encoder, abstracting it away from the user.

**Comment by mappzor** [comment]
> In a semantic encoder interface, I'd further argue that it should be the encoder that picks a good branch variant for the provided offset.

Generally encoder is tasked with picking right sizes for immediates. Issue with branches is about their operands that are relative to RIP past the instruction. Obviously user doesn't know instruction size beforehand, so use cases like rewriting instruction streams with branches become tricky. Same goes for RIP-relative instructions but here the impact is lower because immediates are fixed to 32 bits.

Perhaps in the future we should think about an alternative way of specifying realtives e.g. using addresses. User could specify a virtual address for an instruction and an immediate (`rel` operands) or memory operand with just displacement (`rip-rel` operands). Such value would be interpreted as an address and it would get translated to relative by the encoder (`target_address - (base_virtual_address + instruction_length) = rel_value`). We would need one more piece of information represented somehow to indicate this new mode is used. It would be necessary to diffrentiate from immediate/displacement with an absolute address. At first I thought this concept would nullify the purpose of branching type stuff completely but I no longer think that's the case. I believe an extra "addressing mode" would be a complementary addition but not a replacement for branching type which enables use cases such as simple two pass assemblers (emit instructions with dummy 32-bit immediates first -> patch them later) without having to deal with any addresses at encoder level. This is something for the future though, so let's go back to your suggestion now.

> The upside with the current approach is that it's impossible to specify invalid combinations, reducing the amount of validation required. I assume that's what you meant with "needing a tuple type" in your comment [here](https://github.com/zyantific/zydis/pull/254#discussion_r739657745). However, I personally don't think this warrants the downsides. If such a tuple type is truly required, we should keep it internal to the encoder, abstracting it away from the user.

There aren't many invalid combinations, it will be easy to eliminate them in sanity-checking phase. I see no problems here.

> ZYDIS_BRANCH_TYPE_NONE and ZYDIS_BRANCH_WIDTH_NONE would mean "infer" to the encoder. ZYDIS_BRANCH_TYPE_NONE specifically would mean "infer whether near or short", but never consider "far", which must be requested explicitly. I'd argue that in 99% of cases, users will want some variation of a near/short branch. In a semantic encoder interface, I'd further argue that it should be the encoder that picks a good branch variant for the provided offset.

I fully agree. Scenarios for far branches are uncommon, probably mostly re-encoding existing ones anyway, so `ZYDIS_BRANCH_TYPE_NONE == size-optimal near` sounds good to me. For widths they should be `NONE|8|16|32`. I guess you modeled `ZydisBranchWidth` after existing type which actually specifies effective operand size. I believe we should change it to actual physical size of the operand to make things more intuitive (#266).

**Comment by flobernd** [comment]
I really like your proposal @athre0z. Should be much easier this way.

The idea of having an "absolute addressing mode" for the user to define the input immediates/RIP-rel displacements as well seems like a nice addition for the future. We have to check how far we want to go in this direction tho. We might quickly end up on a higher level ("assembler" vs pseudo-"compiler") like e.g. AsmJit supports it.

> I believe we should change it to actual physical size of the operand to make things more intuitive

I agree. Most user will only care about the physical encoding when manually specifying a branch type different than the NONE/default option.

**Comment by mappzor** [comment]
> The idea of having an "absolute addressing mode" for the user to define the input immediates/RIP-rel displacements as well seems like a nice addition for the future. We have to check how far we want to go in this direction tho. We might quickly end up on a higher level ("assembler" vs pseudo-"compiler") like e.g. AsmJit supports it.

In general I would like to avoid high-level concepts as much as possible, so even this one I would consider highly optional. Support for labels, basic blocks, pseudo-registers, etc. is typically implemented by library users anyway and tailored to needs of their specific projects. From the very beginning I thought about the encoder as a simple, stateless, "backend" component. If higher-level stuff is ever needed I think it would be better to build in on top of the encoder and not as a part of it.

**Comment by flobernd** [comment]
Yes, completely agree. Zydis was always designed as a very low level library.
