### ISSUE TITLE
encoding issue

### ISSUE THREAD

**Issue by brachahl** [zyantific/zydis#289]
When using zydis to decode the instruction 65488b0425005c0100 (mov rax, QWORD PTR gs:0x15c00) and then use zydis to reencode that same instruction that it decoded  I get 656748a1005c010000. (addr32 mov rax, gs:0x15c00)

**Comment by gherzancarolvictor** [comment]
The original instruction had the 0x8B opcode, which required a Mod R/M byte, but also a SIB byte because you cannot encode just a displacement (The '0x15c00' value) in 64-bit mode with the Mod R/M byte alone, which by itself can only be 4-bytes / 32-bits long, making the instruction long.

The encoder took the instruction you gave it, looked at what it did, then built a new, shorter one using the 0xA1 opcode, which takes in a 64-bit offset to a segment (In your case, the 'gs' segment), and then shaved 3 bytes off the instruction by using the 0x67 optional prefix (The 'addr32' you see).

So this is not an issue, the instruction still does the same thing, it's just that the encoder was built by Mappa to encode the shortest instruction it can, and I guess apparently GAS (I assume you used defuse.ca which uses the GNU assembler) has some different logic?

**Comment by mappzor** [comment]
@brachahl Encoder attempts to generate smallest possible output and re-encoded version is shorter while semantics is preserved. I assume the confusing part in your case is address size override. Absolute address you provided fits into 4-byte memory offset operand therefore encoder could optimize size by overriding address size attribute and reducing size of memory offset from 8 bytes to 4 bytes at the cost of adding single extra prefix.
