### ISSUE TITLE
zydis decode error on "fstsw ax"

### ISSUE THREAD

**Issue by ganjue66da** [zyantific/zydis#299]
I found a decode error on fload instruction "fstsw ax".   
Its machine code is "98 df e0", but zydisinfo will decode it as "fwait" whose machine code is "98"

![2022-01-05 10-14-38屏幕截图](https://user-images.githubusercontent.com/71954730/148149927-8fb4d0eb-610e-4415-87c4-58d2420818e5.png)

**Comment by mappzor** [comment]
> Its machine code is "98 df e0", but zydisinfo will decode it as "fwait" whose machine code is "98"

I think you wanted to write 9**B** instead of 9**8**. Zydis behaves correctly, here's a note from Intel SDM:

> The assembler issues two instructions for the FSTSW instruction (an FWAIT instruction followed by an FNSTSW
instruction), and the processor executes each of these instructions separately. If an exception is generated for
either of these instructions, the save EIP points to the instruction that caused the exception.

So actually `9B DF E0` is not a single instruction but two:
```
98 FWAIT
DF E0 FNSTSW AX
```

**Comment by ganjue66da** [comment]
Thank you for your reply, as you said, this is not a bug, this instruction can be split into two instructions.
