### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by cr0mll** [zyantific/zydis#304]
It would be awesome if you fixed your docs. Half the stuff isn't there and the other half has different names from what's actually in the source.

**Comment by flobernd** [comment]
I assume you are referring to the doxygen doc on our website?

This documentation is for *v3*, while our master branch is always bleeding edge (currently beta *v4*).

The version scheme and branching strategy is already mentioned in the README file.

If you feel like using a beta version, you can continue working with the master branch and compile the documentation yourself (there is a Doxyfile in the code).

If you would rather work with the latest stable version and use the online documentation, you should check out the *v3* tag instead of master.

**Comment by athre0z** [comment]
Closing, I think this is largely a duplicate of #112.
