### ISSUE TITLE
Some registers do not have register classes

### ISSUE THREAD

**Issue by rgov** [zyantific/zydis#34]
Just reviewing the table of register classes, the following are missing:

```
// Table registers
ZYDIS_REGISTER_GDTR,   ZYDIS_REGISTER_LDTR,   ZYDIS_REGISTER_IDTR,  ZYDIS_REGISTER_TR,
// Bound registers
ZYDIS_REGISTER_BNDCFG, ZYDIS_REGISTER_BNDSTATUS,
// Misc registers
ZYDIS_REGISTER_MXCSR,  ZYDIS_REGISTER_PKRU,   ZYDIS_REGISTER_XCR0,
```

**Comment by flobernd** [comment]
You are correct, but there is a reason for this: These registers can't be manually encoded in any kind of instruction (e.g. in `modrm.reg`, ...) because they don't have a real register-id like e.g. `RAX` (id=0) and `RCX` (id=1). `IP` and `FLAGS` are exceptions to this rule as they can at least be grouped together by their purpose. The registers in your example all all very different.
