### ISSUE TITLE
When the call is far, zydisdecoderdecodefull cannot work normally

### ISSUE THREAD

**Issue by injertao** [zyantific/zydis#360]
00600000 - FF15 02000000 EB08 8967452301000000 - call 123456789
Zydisdecoderdecodefull will only decode into:
1CA8E63D630 - FF 15 02000000        - call qword ptr [1CA8E63D638]

**Comment by injertao** [comment]
x64 mode:
210E848A - 8B 05 DC4A9D01        - mov eax,[22ABCF6C] { (-1) }
Unable to be decoded correctly, lacking a lot of key data

I'm not sure if it's my problem,

while (ZYAN_SUCCESS(ZydisDecoderDecodeFull(&decoder, code + offset, length - offset,
		&instruction, operands, ZYDIS_MAX_OPERAND_COUNT_VISIBLE,
		ZYDIS_DFLAG_VISIBLE_OPERANDS_ONLY)))

**Comment by injertao** [comment]
I want to reposition a piece of code,

For example:
210E847A - 74 51                 - je 210E84CD
210E847C - 39 83 E4000000        - cmp [rbx+000000E4],eax
210E8482 - 74 12                 - je 210E8496
210E8484 - 89 93 E8000000        - mov [rbx+000000E8],edx
210E848A - 8B 05 DC4A9D01        - mov eax,[22ABCF6C] { (-1) }
210E8490 - 89 83 E4000000        - mov [rbx+000000E4],eax
210E8496 - 8B 83 E8000000        - mov eax,[rbx+000000E8]
210E849C - A8 01                 - test al,01 { 1 }
210E849E - 0F85 23010000         - jne 210E85C7
210E84A4 - 83 C8 01              - or eax,01 { 1 }
210E84A7 - 89 83 E8000000        - mov [rbx+000000E8],eax
210E84AD - F3 44 0F10 9B CC000000  - movss xmm11,[rbx+000000CC]
210E84B6 - F3 44 0F59 9B C8000000  - mulss xmm11,[rbx+000000C8]
210E84BF - F3 44 0F11 9B EC000000  - movss [rbx+000000EC],xmm11
210E84C8 - E9 03010000           - jmp 210E85D0
210E84CD - 39 83 E4000000        - cmp [rbx+000000E4],eax
210E84D3 - 74 12                 - je 210E84E7
210E84D5 - 89 93 E8000000        - mov [rbx+000000E8],edx
210E84DB - 8B 05 8B4A9D01        - mov eax,[22ABCF6C] { (-1) }
210E84E1 - 89 83 E4000000        - mov [rbx+000000E4],eax
210E84E7 - 8B 83 E8000000        - mov eax,[rbx+000000E8]
210E84ED - A8 01                 - test al,01 { 1 }
210E84EF - 0F85 D2000000         - jne 210E85C7
210E84F5 - 83 C8 01              - or eax,01 { 1 }
210E84F8 - 89 83 E8000000        - mov [rbx+000000E8],eax
210E84FE - 48 8B B3 80000000     - mov rsi,[rbx+00000080]
210E8505 - 48 85 F6              - test rsi,rsi
210E8508 - 0F84 86000000         - je 210E8594
210E850E - F3 0F10 4E 04         - movss xmm1,[rsi+04]
210E8513 - F3 0F10 06            - movss xmm0,[rsi]
210E8517 - F3 0F10 56 08         - movss xmm2,[rsi+08]
210E851C - F3 0F59 C0            - mulss xmm0,xmm0
210E8520 - F3 0F59 C9            - mulss xmm1,xmm1
210E8524 - F3 0F58 C1            - addss xmm0,xmm1
210E8528 - F3 0F59 D2            - mulss xmm2,xmm2
210E852C - F3 0F58 C2            - addss xmm0,xmm2
210E8530 - 0F2F C6               - comiss xmm0,xmm6
210E8533 - 76 0C                 - jna 210E8541
210E8535 - E8 D6DA8100           - call 21906010 { ->->739A5DEC }

Move it to a new address and recalculate the relative address

**Comment by mappzor** [comment]
> 00600000 - FF15 02000000 EB08 8967452301000000 - call 123456789
Zydisdecoderdecodefull will only decode into:
1CA8E63D630 - FF 15 02000000 - call qword ptr [1CA8E63D638]

`ZydisDecoderDecodeFull` decodes first instruction from that byte stream which is `call qword ptr ds:[rip+0x02]`. In your case you provided runtime address of `1CA8E63D630`, so `1CA8E63D630 + 6 (instruction length) + 2 (displacement) = 1CA8E63D638`. Everything seems to be fine here.

>210E848A - 8B 05 DC4A9D01 - mov eax,[22ABCF6C] { (-1) }
Unable to be decoded correctly, lacking a lot of key data

What's the problem here? What "key data" is missing? Zydis decodes this as `mov eax, dword ptr ds:[rip+0x19D4ADC]`, so again: `210E848A + 6 (instruction length) + 19D4ADC (displacement) = 22ABCF6C`. Everything is fine here as well.

You seem to be having trouble with understanding how RIP-relative operands work. Decoding process itself does not depend on runtime address. In above example (`mov eax, dword ptr ds:[rip+0x19D4ADC]`) Zydis will decode 2nd operand as memory operand with `operand.mem.base == ZYDIS_REGISTER_RIP` and `operand.mem.disp.value == 0x19D4ADC`. That's raw data in decoded operand structure. All the math to take runtime address into account is done inside the formatter. If you need to perform such calculations for your own needs use `ZydisCalcAbsoluteAddress`.

**Comment by injertao** [comment]
@mappzor Thank you for your answer, but my first question doesn't seem to have been solved.
00600000 - FF15 02000000 EB08 8967452301000000 - call 123456789
Zydisdecoderdecodefull will only decode into:
1CA8E63D630 - FF 15 02000000 - call qword ptr [1CA8E63D638]

**Comment by flobernd** [comment]
`FF15 02000000 EB08 8967452301000000` is not a single instruction:

```
0:  ff 15 02 00 00 00       call   DWORD PTR ds:0x2
6:  eb 08                   jmp    0x10
8:  89 67 45                mov    DWORD PTR [edi+0x45],esp
b:  23 01                   and    eax,DWORD PTR [ecx]
d:  00 00                   add    BYTE PTR [eax],al
```

**Comment by injertao** [comment]
@flobernd 
Maybe you can check this code through cheatengine.
0xFF,0x15,0x02,0x00,0x00,0x00,0xEB,0x08,0x89,0x67,0x45,0x23,0x01,0x0,0x0,0x0
Then use zydis to decode

**Comment by injertao** [comment]
![image](https://user-images.githubusercontent.com/56824344/177976147-8e41b3ee-f874-46c6-9d61-16468437cdbe.png)
In x64, this is a single instruction

**Comment by flobernd** [comment]
Yeah, you are looking at a RIP-rel instruction (like @mappzor explained to you).

```
0:  ff 15 02 00 00 00       call   QWORD PTR [rip+0x2]        # 0x8
```

This points to the memory `[rip+0x2]` -> `[8]` at which you find the payload `8967452301000000` (the target address).

**Comment by injertao** [comment]
@flobernd 
Thank you for your answer, but I still can't understand. How can I get the same decoding as cheatengine?

**Comment by flobernd** [comment]
The generic solution is very complex (you have to create a control flow graph).

If it's **always** this specific case all the time, you could try to detect that pattern and jump over the data payload. Something like (pseudo code):

```
if (instr.mnemonic == CALL && instr.operands[0].base == RIP && instr.operands[0].disp == 2)
{
    code += 10; // payload is 8 byte in 64-bit mode + 2 byte are placed inbetween (EB08)
    offset += 10;
}
...
```

**Comment by flobernd** [comment]
Btw. CheatEngine is actually not 100% correct as well. It fails to calculate the destination correctly. The last `add [rax], al` is not an actual instruction, but still belongs to the data payload.

**Comment by injertao** [comment]
@flobernd 
The last instruction is wrong, which is meaningless, because I applied for an empty memory, just to demonstrate an instruction

**Comment by tremalrik** [comment]
This issue seems very similar to issue #188 from a year ago - what happens appears to be that someone somewhere has come up with some cute code idioms to express functionality that does not natively exist as x86 instructions (jmp/call with absolute address), and with both #188 and this issue, CheatEngine will recognize the idiom and display it as an instruction, even though it really isn't.

Looking at CheatEngine's disassembler source code (see e.g. https://github.com/cheat-engine/cheat-engine/blob/master/Cheat%20Engine/disassembler.pas#L15381 ), its recognizers appear to be very specific - CheatEngine will very specifically recognize exactly the 8-byte sequence `ff 15 02 00 00 00 eb 08` as the first 8 bytes of a call-absolute-address instruction (with the next 8 bytes being the absolute-address) and display it as such.

Since this construct is not a 'real' instruction - it consists of two instructions and one 64-bit data item, after all - it's not going to be recognized by Zydis as such (nor do I think it should be). If OP wants to recognize it, they should probably add their own test specifically for the 8-byte `ff 15 02 00 00 00 eb 08` sequence.

(similarly, for the jump in issue #188, if CheatEngine-like behavior is what they want, they should add their own test for the 6-byte sequence `ff 25 00 00 00 00`.)

**Comment by Originns** [comment]
As far as I can tell, both of these issues (#188 and this one) originate from MinHook. MinHook is a hooking library which allocates rwx memory for their trampoline allowing them to mix data and code for this weird jmp/call to an absolute address (see https://github.com/TsudaKageyu/minhook/blob/4a455528f61b5a375b1f9d44e7d296d47f18bb18/src/trampoline.c#L79)

**Comment by athre0z** [comment]
Closing because this is not actually an issue in Zydis.
