### ISSUE TITLE
Bad instruction and asserts

### ISSUE THREAD

**Issue by gdbinit** [zyantific/zydis#39]
Hi,

Getting an assert on the following bytes: 64 62 b1 f8 0d 18 31
Assertion failed: (instruction->operandCount >= 2), function ZydisDecodeOperands, file /Users/xxxxx/zydis/src/Decoder.c, line 2006. A few variations of the last byte also produce the same result.

The core question is if asserts are to stay in the code base or they will be removed in the near future? The reason is that I am mass analysing potentially hostile binaries and getting into weird decodings like this and that will crash my daemon, unless I write something to intercept those assertions and recover from them. 

Are these kind of instructions interesting to you to return proper errors? I'll probably land into a bunch of them on my side.

Best,
Pedro

P.S.: sort of ignore the asserts as development feature since I just saw I asked that long time ago in another bug. In this particular case I fixed the assert into a test for operandCount < 2 and return a ZYDIS_STATUS_DECODING_ERROR if true. Might be better than the assert but didn't really check the EVX instructions to see if it's the best solution.

**Comment by athre0z** [comment]
Hi,

our [fuzzing daemon](https://fuzzer.zydis.re/) (we have a server of mine fuzzing through Zydis in its idle time) found this one a few weeks ago, however it looks like Flo accidentally[ pushed the fix to `future`](https://github.com/zyantific/zydis/commit/e6dbba0bd314680dda64ef34e56cd12046ae8a2d) (our v3.0 branch with breaking API changes) instead of `develop`, preventing it from being merged into v2.0.1. I'll cherry-pick it over to `develop`, thanks for letting us know!

For everyone who might find this issue via Google, the question regarding asserts is answered [here](https://github.com/zyantific/zydis/issues/17#issuecomment-329522271).

**Comment by athre0z** [comment]
Due to various conflicts it became more of a backport than a cherry-pick. Anyhow, the fix is up on develop now!

https://github.com/zyantific/zydis/commit/1aa5e648f177b05e522ecce088bf400f78015f8c
