### ISSUE TITLE
Add possibility of not ignoring segment override prefix

### ISSUE THREAD

**Issue by Ariurn** [zyantific/zydis#402]
### Problem:
Sometimes instructions contain **segment override prefix (cs, ds, ss, es)**.
Zydis decodes them properly, but doesn't want to encode them back.
As I suppose, Zydis marks them to ignore in the future.
Please, add possibility of not ignoring SOP (or tell how to do it).

### Output:
```
Before zydis: 3e 48 8b 5b 18
0000000000000000  mov rbx, [rbx+0x18]

After zydis: 48 8b 5b 18
0000000000000000  mov rbx, [rbx+0x18]
```

### Code:
```
#include <Windows.h>
#include <stdio.h>
#include <inttypes.h>
#include <string.h>
#include "Zydis/Zydis.h"

static void ExpectSuccess(ZyanStatus status)
{
    if (ZYAN_FAILED(status))
    {
        fprintf(stderr, "Something failed: 0x%08X\n", status);
        exit(EXIT_FAILURE);
    }
}

int main()
{
    // Initialize buffer with instruction
	ZyanU8 asm_buf[] = { 0x3E, 0x48, 0x8B, 0x5B, 0x18}; // mov    rbx,QWORD PTR ds:[rbx+0x18]
	ZyanUSize asm_size = sizeof(asm_buf) / sizeof(asm_buf[0]);

    // Print instruction hex before zydis
    printf("Before zydis: ");
    for (ZyanUSize i = 0; i < asm_size; ++i)
    {
        printf("%02" PRIx8 " ", asm_buf[i]);
    }
    printf("\n");

    // Init decoder, formatter
    ZydisDecoder decoder;
    ZydisDecoderInit(&decoder, ZYDIS_MACHINE_MODE_LONG_64, ZYDIS_STACK_WIDTH_64);
    ZydisFormatter formatter;
    ZydisFormatterInit(&formatter, ZYDIS_FORMATTER_STYLE_INTEL);

    ZyanUSize offset = 0;
    ZydisDecodedInstruction instruction;
    ZydisDecodedOperand operands[ZYDIS_MAX_OPERAND_COUNT];
    while (offset < asm_size)
    {
        // Print format instruction before zydis
        ExpectSuccess(ZydisDecoderDecodeFull(&decoder, asm_buf + offset, asm_size - offset, &instruction, operands));
        printf("%016" PRIX64 "  ", offset);
        char buffer[256];
        ZydisFormatterFormatInstruction(&formatter, &instruction, operands,
            instruction.operand_count_visible, buffer, sizeof(buffer), offset, ZYAN_NULL);
        puts(buffer);

        // Convert instruction to request
        ZydisEncoderRequest enc_req;
        ExpectSuccess(ZydisEncoderDecodedInstructionToEncoderRequest(&instruction, operands, instruction.operand_count_visible, &enc_req));

        // Convert instruction to request
        uint8_t new_bytes[ZYDIS_MAX_INSTRUCTION_LENGTH];
        ZyanUSize new_instr_length = sizeof(new_bytes);
        ExpectSuccess(ZydisEncoderEncodeInstruction(&enc_req, new_bytes, &new_instr_length));

        // Print instruction hex after zydis
        printf("\nAfter zydis: ");
        for (ZyanUSize i = 0; i < new_instr_length; ++i)
        {
            printf("%02" PRIx8 " ", new_bytes[i]);
        }
        printf("\n");
        
        // Print format instruction after zydis
        ExpectSuccess(ZydisDecoderDecodeFull(&decoder, asm_buf + offset, asm_size - offset, &instruction, operands));
        printf("%016" PRIX64 "  ", offset);
        ZydisFormatterFormatInstruction(&formatter, &instruction, operands, instruction.operand_count_visible, buffer, sizeof(buffer), offset, ZYAN_NULL);
        puts(buffer);

        // Increase offset
        offset += instruction.length;
    }

    return 0;
}
```

**Comment by mappzor** [comment]
This is expected behavior. Encoder aims for smallest possible output and whole API is semantic-driven (#254) so by design it doesn't give you control over physical encoding details (encoder doesn't insert **redundant or useless prefixes**, you cannot select longer VEX variant, etc.). In 64-bit mode encoder will refuse to encode CS, DS, ES and SS overrides (it will fail with `ZYAN_STATUS_INVALID_ARGUMENT`) because those prefixes are ignored by the hardware:
> In 64-bit mode: CS, DS, ES, SS are treated as if each segment base is 0, regardless of the value of the associated
segment descriptor base. This creates a flat address space for code, data, and stack. FS and GS are exceptions.
Both segment registers may be used as additional base registers in linear address calculations (in the addressing
of local data and certain operating system data structures).
(...)
Limit checks for CS, DS, ES, SS, FS, and GS are disabled in 64-bit mode.

Decoder decodes and ignores those prefixes (#231). That's actually why your example works. You can easily see what happes in ZydisInfo.
```
ZydisInfo -64 3E 48 8B 5B 18
ATTRIBUTES: HAS_MODRM HAS_REX ACCEPTS_SEGMENT
// Later in output you will see byte by byte instruction breakdown, 3E prefix will be shown in grey (ignored)
```
Situation will look differently if we try similar instruction in 32-bit mode:
```
ZydisInfo -32 3E 8B 5B 18
ATTRIBUTES: HAS_MODRM ACCEPTS_SEGMENT HAS_SEGMENT HAS_SEGMENT_DS
// Later in output you will see byte by byte instruction breakdown, 3E prefix will be shown in purple (valid prefix)
```
Internally `ZydisEncoderDecodedInstructionToEncoderRequest` looks up those `HAS_SEGMENT_*` flags to decide which prefixes will be requested from the encoder. In your case it's never requested (you can try setting `HAS_SEGMENT_DS` manually after `ZydisEncoderDecodedInstructionToEncoderRequest` but then encoding will fail on sanity checks as intended).

Why are you trying to preserve that ignored prefix?

**Comment by Ariurn** [comment]
First of all, sorry for late answer, had a tough week :)
It's really good that the library aims for smallest possible output.
The purpose of my program is that I decode instructions one by one, change those that are necessary, and then encode them back.
Due to the problem above, it turns out that some output instructions have a shorter length. Because of this, all instructions below will have different offsets, which will break addressing in the program.
Luckily, at the moment I've found a simple and, I hope, working solution: place nops after instructions, that became shorter.

**Comment by mappzor** [comment]
That's the proper way to handle this. We even have `ZydisEncoderNopFill` to help with optimal padding. However if you are doing binary rewriting without ability to readjust instructions to different addresses you need to be careful about changes you are making. It's easy to end up with bigger instructions e.g. due to extra `REX` prefix and that cannot be fixed so easily.

**Comment by Ariurn** [comment]
I've used this great function, it saved my time :)
Yes, I've already got similar problem during changing operand of jz opcode from 8-bit to 16-bit (because of it became greater than 127). But I gonna handle this, just need some time for research. I'm going to decode assembly complexly, remembering all significant information (original offsets, references, etc). So, I'll be able to fix all addressing problems and reassemble it.

**Comment by flobernd** [comment]
Maybe this piece of code is useful for you as an inspiration:

https://github.com/zyantific/zyan-hook-engine/blob/master/src/Relocation.c

It's not updated to the latest Zydis version and does not make use of the encoder yet, but it is able to handle shifted instruction offsets due to enlarged instructions.

**Comment by Ariurn** [comment]
Thanks a lot, will take a look :) I hope it'll be very helpful
