### ISSUE TITLE
[HELP] OperandDefinitions.inc Need a C89 style define file.

### ISSUE THREAD

**Issue by Hacksign** [zyantific/zydis#447]
Hi there,

I'm working on an old project which compiler only support C89 standard. It is un-acceptable using `.lib` file to compile the project.

I've done a modification to meet C89 standard with almost all source codes, but there is a file called `OperandDefinitions.inc` under `src/Generated/`, It's a huge declaration file, and I don't find how to generate it.

So, is there an exists declaration file which meet C89 standard, or, is there any document describe how to generate it ?

**Comment by flobernd** [comment]
Hi @Hacksign,

currently Zydis requires a C11 compatible compiler and therefore we do not provide support for older standards. The generator project is located in this repository: https://github.com/zyantific/zydis-db

It is possible to modify that project in order to customize generation of the `.inc` files, however, this project is written in Delphi/Pascal which usually is something most people don't feel comfortable with.

If you don't know Delphi/Pascal very well, my recommendation would be to parse the existing `.inc` file and transform it.

**Comment by Hacksign** [comment]
@flobernd  Thanks~ I will try convert it manually~
