### ISSUE TITLE
WinDDK is not supported.

### ISSUE THREAD

**Issue by wonderzdh** [zyantific/zydis#60]
hi:
When I use C:\WinDDK\7600.16385.1 to build this, I will encounter many problems.

like this:

> case ZYDIS_REG_ENCODING_OPCODE:
        {
            ZYDIS_ASSERT((registerClass == ZYDIS_REGCLASS_GPR8) ||
                         (registerClass == ZYDIS_REGCLASS_GPR16) ||
                         (registerClass == ZYDIS_REGCLASS_GPR32) ||
                         (registerClass == ZYDIS_REGCLASS_GPR64));
            ZydisU8 value = (instruction->opcode & 0x0F);                                << faild!
            if (value > 7)
            {
                value = value - 8;
            }
            return value;
        }

or

> static ZydisStatus ZydisDecodeOperandMemory(ZydisDecoderContext* context,
    ZydisDecodedInstruction* instruction, ZydisDecodedOperand* operand,
    ZydisRegisterClass vidxRegisterClass)
{
    ZYDIS_ASSERT(context);
    ZYDIS_ASSERT(instruction);
    ZYDIS_ASSERT(operand);
    ZYDIS_ASSERT(instruction->raw.modrm.isDecoded);
    ZYDIS_ASSERT(instruction->raw.modrm.mod != 3);
    ZYDIS_ASSERT(!vidxRegisterClass || ((instruction->raw.modrm.rm == 4) &&
        ((instruction->addressWidth == 32) || (instruction->addressWidth == 64))));
    operand->type = ZYDIS_OPERAND_TYPE_MEMORY;
    operand->mem.type = ZYDIS_MEMOP_TYPE_MEM;
    const ZydisU8 modrm_rm = instruction->raw.modrm.rm;                            << faild!
    ZydisU8 displacementSize = 0;                                                                      << faild!

The problem is that the location of the variable is not declared in the first line.

**Comment by flobernd** [comment]
Hi there. What compiler version are you using? We tested the driver compatibility some time ago witthout any problems (there is a VS project file in the `msvc` directory.

Your compiler has to support the C99 standard. C98 and earlier does not allow to declare variables in the mid of a function.

**Comment by wonderzdh** [comment]
hi, Our project uses WDK 7600.16385.1.This is a very old version, But only it supports windows xp. WDK8 or later  minimum supported version is window 7.
I use the command line compiler that comes with it.It does not support C99. So I may need to manually modify these errors.

**Comment by flobernd** [comment]
Shouldn't it be possible to use the old XP-compatible WDK version with a more recent compiler toolchain? I remember Visual Studio shipping a Windows XP platform toolset.

**Comment by wonderzdh** [comment]
hi:
I created a new branch and fixed the support for C98.

https://github.com/wonderzdh/zydis

**Comment by Mattiwatti** [comment]
I know I'm replying to a months-old issue that you seem to already have resolved yourself, but there is in fact a way to make the WDKs 8 through 10 support XP, or even NT 4.0 and Windows 2000. It is somewhat hacky, but not so much that I would consider using an ancient DDK without C99 support a serious alternative. You also get the benefits of being able to use VS (if you want), and generally vastly improved codegen since compiler developers haven't been sitting still for 10 years.

So, in my not so humble opinion you should not 'fix' this by making Zydis C98 compliant, but rather by using a toolchain that isn't a decade old so you can compile C99 projects. This includes Zydis and any other dependencies you may want to add in the future (hint: most won't be C98 compliant).

Steps:
1. Make a standard WDM driver project that uses the Windows 10 WDK toolchain. In the project properties, go to Driver Settings and set the target OS to Windows 7, since that's the lowest possible value. Trying to override `NTDDI_VERSION` and co the standard way via the project preprocessor directives will not work.
2. Instead, on the same properties page, go to C/C++ -> Advanced and edit the 'forced include file' (the default value should be `$(KIT_SHARED_IncludePath)\warning.h`). Change this to add, say, `winver.h` by changing it to `$(KIT_SHARED_IncludePath)\warning.h;winver.h`.
3. Add a `winver.h` file in the project root directory and add it to the project. Here is an example you can use:
```C++
#pragma once

// Do not use this file when compiling for blasphemous architectures such as ARM
#if defined(_M_IX86) || defined(_WIN64)

#undef WINVER
#undef _WIN32_WINNT
#undef NTDDI_VERSION

#ifdef _M_IX86
// This is for XP support (NT 5.1), but you can go as low as you want
#define WINVER 0x0501
#define _WIN32_WINNT 0x0501
#define NTDDI_VERSION 0x05010000
#elif defined(_WIN64)
// x64 or Itanium; require NT 5.2 (Server 2003 or XP x64)
#define WINVER 0x0502
#define _WIN32_WINNT 0x0502
#define NTDDI_VERSION 0x05020000
#endif

#endif
```
4. Copy `ntoskrnl.lib` for x86 and (if it exists) x64 from the DDK of whichever version of Windows you want to compile for and put them somewhere in your solution directory - let's say `/lib/x86` and `/lib/x64` respectively. Repeat this step for any other static dependencies you may have (`hal.lib`, `win32k.lib`, and so on).
5. Go back to the project properties, and this time go to Linker -> Input. The default value is `%(AdditionalDependencies);$(KernelBufferOverflowLib);$(DDK_LIB_PATH)ntoskrnl.lib;$(DDK_LIB_PATH)hal.lib;$(DDK_LIB_PATH)wmilib.lib`, which is super bad. If you only need `ntoskrnl.lib`, delete everything in this field and replace it with `lib/<arch>/ntoskrnl.lib`. You may want to also append `$(KernelBufferOverflowLib)`, which is required if you use `/GS`.
6. Under Linker -> General, set 'Version' to e.g. `5.1` for XP x86. Under Linker -> System, set 'Minimum required version' to `5.01`.

Step (3) ensures that you cannot accidentally use any functions that do not exist on <target version> at compile time, and step (5) does the same at link time. This makes it impossible to make a driver that compiles but does not run. Step (6) is theoretically needed to ensure the loader won't refuse your driver because the subsystem version is too high, but I've found that in practice this value is ignored by the kernel. This is not so in user mode.

One note re: `/GS`: if you use this, the Target OS version under Driver Settings absolutely **must** be set to Windows 7, because otherwise `$(KernelBufferOverflowLib)` will evaluate to `bufferoverflowfastfailk.lib`, which uses `int 29h` (`CD 29`) to issue an `RtlFailFast(FAST_FAIL_GS_COOKIE_INIT)` bugcheck in `__security_init_cookie()` if `__security_cookie` is equal to the default value of `2B992DDFA232h`. This is because on Windows 8 and later, the loader initializes the cookie. Because (A) the loader does not initialize the cookie on Windows 7 and below, and (B) `int 29h` is an unexpected interrupt on those platforms, this will give you a very hard to debug driver that will BSOD immediately upon load. If you do **not** use `/GS`, you must change the driver entry point in the project settings (Linker -> Advanced -> Entry Point) from `GsDriverEntry` to `DriverEntry`. Otherwise you will get an unresolved external error at link time.

**Comment by wonderzdh** [comment]
> 我知道我正在回答你似乎已经解决了几个月的问题，但事实上有一种方法可以让WDK 8到10支持XP，甚至NT 4.0和Windows 2000.它有点hacky但不是那么多，我会考虑使用没有C99的古老DDK支持一个严肃的选择。您还可以获得使用VS（如果需要）的好处，并且通常会大大改进codegen，因为编译器开发人员已经静止了10年。
> 
> 因此，在我不那么谦虚的意见中，你不应该通过使Zydis C98兼容而“修复”这个，而是使用不是十年之久的工具链，这样你就可以编译C99项目。这包括Zydis以及您将来可能要添加的任何其他依赖项（提示：大多数不符合C98）。
> 
> 脚步：
> 
> 1. 制作使用Windows 10 WDK工具链的标准WDM驱动程序项目。在项目属性中，转到“驱动程序设置”并将目标操作系统设置为Windows 7，因为这是可能的最低值。尝试`NTDDI_VERSION`通过项目预处理程序指令覆盖和协调标准方法将不起作用。
> 2. 相反，在相同的属性页面上，转到C / C ++  - > Advanced并编辑'强制包含文件'（默认值应该是`$(KIT_SHARED_IncludePath)\warning.h`）。将此更改为添加，例如，`winver.h`将其更改为`$(KIT_SHARED_IncludePath)\warning.h;winver.h`。
> 3. `winver.h`在项目根目录中添加一个文件并将其添加到项目中。以下是您可以使用的示例：
> 
> ```c++
> ＃编译一次
> 
> //在编译ARM 
> ＃如果定义（_M_IX86）||等亵渎性架构时不要使用此文件 定义（_WIN64）
> 
> ＃民主基金 WINVER
> ＃民主基金 _WIN32_WINNT
> ＃民主基金 NTDDI_VERSION
> 
> ＃IFDEF _M_IX86
>  //这是XP的支持（NT 5.1），但你可以去，只要你想低 
> ＃定义 WINVER  0x0501 
> ＃定义 _WIN32_WINNT  0x0501 
> ＃定义 NTDDI_VERSION  0x05010000 
> ＃elif的定义（_WIN64）
>  // 64或安腾; 需要NT 5.2（Server 2003或XP x64）的 
> ＃定义 WINVER  0x0502 
> ＃定义 _WIN32_WINNT  0x0502 
> ＃定义 NTDDI_VERSION  0x05020000 
> ＃ENDIF
> 
> ＃ENDIF
> ```
> 
> 1. 复制`ntoskrnl.lib`从哪个版本的Windows要编译并把他们的地方在解决方案目录中DDK x86和（如果存在的话）64 -假设`/lib/x86`和`/lib/x64`分别。对于您可能拥有的任何其他静态依赖项（`hal.lib`，`win32k.lib`等等），重复此步骤。
> 2. 返回项目属性，这次转到链接器 - >输入。默认值是`%(AdditionalDependencies);$(KernelBufferOverflowLib);$(DDK_LIB_PATH)ntoskrnl.lib;$(DDK_LIB_PATH)hal.lib;$(DDK_LIB_PATH)wmilib.lib`，这是超级糟糕的。如果您只需要`ntoskrnl.lib`，请删除此字段中的所有内容并将其替换为`lib/<arch>/ntoskrnl.lib`。您可能还想要附加`$(KernelBufferOverflowLib)`，如果您使用，则需要附加`/GS`。
> 3. 在链接器 - >常规下，将“版本”设置为例如`5.1`XP x86。在链接器 - >系统下，将“最低要求版本”设置为`5.01`。
> 
> 步骤（3）确保您不会在编译时意外地使用$ version上不存在的任何函数，并且步骤（5）在链接时也会这样做。这使得编译但不运行的驱动程序成为不可能。理论上需要步骤（6）来确保加载器不会拒绝您的驱动程序，因为子系统版本太高，但我发现实际上这个值被内核忽略了。用户模式不是这样。
> 
> 需要注意的一点是`/GS`：如果你使用它，驱动程序设置下的目标操作系统版本绝对**必须**设置为Windows 7，否则`$(KernelBufferOverflowLib)`将评估为`bufferoverflowfastfailk.lib`，如果等于默认值，则使用`int 29h`（`CD 29`）发出`RtlFailFast(FAST_FAIL_GS_COOKIE_INIT)`错误检查。这是因为在Windows 8及更高版本中，加载程序初始化cookie。因为（A）加载器没有在Windows 7及更低版本上初始化cookie，并且（B）在这些平台上是一个意外的中断，这将为您提供一个非常难以调试的驱动程序，它将在加载后立即进行BSOD。如果**不**使用，则必须在项目设置（链接器 - >高级 - >入口点）中更改驱动程序入口点`__security_init_cookie()``__security_cookie``2B992DDFA232h``int 29h`****`/GS``GsDriverEntry`到`DriverEntry`。否则，您将在链接时获得未解决的外部错误。

Thank you very much for your detailed answer, I have used this method to compile the driver in a new project. Of course, the old project will still not upgrade the compiler (it is gradually being abandoned)
