### ISSUE TITLE
rva

### ISSUE THREAD

**Issue by DiskGetor** [zyantific/zydis#79]
how to out rva model for fix jnz xx,jmp  xxx and so on based begin addres and write them to allocal mem ? i am trying to copy the size of 0x600 codes above to the new address of allocal mem ,but the jnz xx is not rva value based start address,can you help me again? thank you.

**Comment by Mattiwatti** [comment]
Let me give it a try...

Since you're asking about RVAs and not offsets, I'm going to make two assumptions:
1. You are disassembling a `SEC_IMAGE` mapping (usually this is simply a loaded DLL or exe), **not** a `SEC_COMMIT` mapping (e.g. the result of `LoadLibraryExW(..., LOAD_LIBRARY_AS_DATAFILE)` or doing `ReadFile()` into a buffer you allocated yourself).
2. By 'start address' you mean the base of this image, since that is what the 'relative' part of an RVA is... relative to. Sorry if that's condescending, but your question really is kinda difficult to decipher...

If so, and you want the RVA of e.g. a `jmp` target from the instruction operand, do:
```C
ZyanU64 *targetAddress;
ZydisCalcAbsoluteAddress(&instruction, &instruction.operands[0], runtimeAddress, &targetAddress);
DWORD rva = (DWORD)(targetAddress - runtimeBase); // This is why a CS degree requires maths
```
Here I'm assuming you previously obtained a `ZyanU64 runtimeBase` for the image, which may correspond to the address of an actual image in memory, but (like the instruction) doesn't have to. The resulting RVA will be the same.

**Comment by DiskGetor** [comment]
> 指令操作数的目标，请执行以下操

yes,i will try,like these web:

https://github.com/zyantific/zyan-hook-engine/issues/2

https://rammichael.com/multiline-ultimate-assembler-library

![image](https://user-images.githubusercontent.com/19886504/48752904-8e4eaa80-ecc6-11e8-8a8f-c0a7143dfd6e.png)

and i need a like https://github.com/x64dbg/XEDParse project, and do you want to post one?
