### ISSUE TITLE
Alignment issues due to pack pragma's

### ISSUE THREAD

**Issue by gdbinit** [zyantific/zydis#83]
Hi,

I am having some alignment related issues in macOS due to pack pragmas used in a few Zydis data structures. macOS linker doesn't like the resulting unaligned addresses. I have removed them and I don't see any side effects (I wasn't expecting any anyway). The comments mention that they are used to save space, which is understandable given some Zydis embedded goals. The question is if they are really needed or something could be introduced to distinguish between embedded and "normal" systems where wasting the alignment space memory isn't really a big problem?

Thanks!

**Comment by flobernd** [comment]
Hey there,

you are correct, the `#pragma pack`s are only used to save up some bytes and there shouldn't be any side-effects if you just remove them. I tested the performance on my system (Intel Core i9-7900X) and the binary _with_ packing was even faster (which surprised me, but I never investigated any further). For this reason I'm not sure if disabling the packing on all non-embedded devices is the right thing to do. But we can of course disable it for macOS targets.

Are you sure this is a general problem on macOS or do you use a special linker? @athre0z did you encounter similar issues on macOS as well?

**Comment by athre0z** [comment]
Nope, it's working fine for me with the default toolchain on Mojave 10.14.2.

I'd prefer not to remove these packs. Despite binary size being less relevant on modern hardware, it has been one of our core selling points towards the "oldschool" people. IIRC, removing the alignments increases binary size by something in the range of 25% and, as @flobernd mentioned, perhaps counter-intuitively, also results in a minor decrease in performance (due to good L1 cache use being more important than aligned addresses on X86, I'd guess).

**Comment by flobernd** [comment]
Closing this for now.
