### ISSUE TITLE
Set Zydis include paths as project-relative, not solution-relative

### ISSUE THREAD

**Issue by HoShiMin** [zyantific/zydis#91]
It is necessary when you want to add Zydis project as subproject to another solution without Zydis.vcxproj modification (when it presents in project as git submodule)

**Comment by flobernd** [comment]
@Mattiwatti Would be cool if you could take a look at this, if you have some spare time 😄

**Comment by HoShiMin** [comment]
And if we say about default project hierarchy it would be great if x86/x64/debug/release output folders will be different, coz look this case: let's add Zydis as submodule into our custom project, then add Zydis.vcxproj into solution, setup the building order and look: build the x86 project and then switch to the x64 mode and build again. Zydis will not rebuild and we'll get the failure, because for the x64 project we'll have x86 Zydis *.lib file in the /bin directory, alright?

So, the solution of this is modify the Zydis.vcxproj file, but it is dirty solution, because it requires to fork Zydis (but I want to add it as submodule).

**Comment by Mattiwatti** [comment]
I agree this would be better, I ran into the same issue myself when adding Zydis as a submodule of another repository. I will have a look at this probably sometime this week.

**Comment by Mattiwatti** [comment]
Re: the x86/x64 output directory issue: I tried reproducing this with no luck (i.e. it rebuilds the .lib correctly with the new bitness), but then I remembered that this is because I explicitly set up the dependencies in the .sln file. This means that in the Zydis-provided .sln, the user mode examples depend on Zycore and Zydis, the kernel mode example depends on Zydis, and Zycore and Zydis do not have dependencies.

If you set up your own solution similar to the above (right click the Zydis-using project -> `Build Dependencies` -> `Project Dependencies`) rebuilding should work as intended. However I'm not opposed to outputting to e.g. `bin/x86` and `bin/x64` respectively. I have a slight preference for simply `bin` because it's one less level to browse to, but it does mean that changing the bitness will destroy the previous build output. But the same argument can be made for the build configurations (Debug vs Release, and user vs kernel mode), and this is in fact the MSVC default, e.g. `x64/Release`. I don't see much point in adding a subdirectory for every build configuration and bitness combination to be honest, but I'm open to suggestions/arguments for either `bin` or `bin/<arch>`.
